name: Feature request
description: Suggest an improvement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
